/* Two-player, host-authoritative co-op. Room discovery uses PeerJS Cloud; gameplay uses WebRTC. */
const COOP_LEVELS=['The Forgotten Wing','The Broken Staircase','The Last Inheritance'];
const coop={active:false,host:false,peer:null,connection:null,code:'',ready:false,remoteReady:false,started:false,players:[],floors:[],keys:{stair:false,exit:false},clues:[false,false],lives:3,stage:1,ended:false,clock:0,netClock:0};
const solo={tick,updateUI,persist,goHome,start:$('start').onclick,deviceComputer:$('chooseComputer').onclick,devicePhone:$('choosePhone').onclick};
function coopStatus(message){$('roomStatus').textContent=message;}
function coopSend(data){if(coop.connection?.open)coop.connection.send(data);}
function coopId(){return coop.host?0:1;}
function coopLocal(){return coop.players[coopId()];}
function coopBindWorld(){const p=coopLocal();if(!p||!coop.floors[p.floor])return;world=coop.floors[p.floor];world.player=p;world.lives=coop.lives;world.stamina=p.stamina;}
function coopTeammates(){return coop.started&&!coop.ended?coop.players.filter((p,i)=>i!==coopId()&&p.floor===coopLocal()?.floor&&!p.hidingId):[];}
function coopLeave(){coop.started=false;coop.active=false;stopHeartbeat();stopFootsteps();stopCreaks();stopPictureSounds();stopScreams();coop.connection?.close();coop.peer?.destroy();coop.peer=null;coop.connection=null;coop.ready=false;coop.remoteReady=false;$('start').onclick=solo.start;coop.players=[];coop.floors=[];world=null;mode='home';canvas.style.filter='none';$('settingsHome').textContent='Save & return home';$('coopHud').hidden=true;$('coopInteract').hidden=true;KEY=difficulty==='psycho'?'hollow-house-psycho-v1':'hollow-house-v1';level=1;best=0;stageSaves={};try{const s=JSON.parse(localStorage.getItem(KEY));if(s){level=s.level||1;best=s.best||0;stageSaves=s.stageSaves||{};world=stageSaves[level]||null;}}catch{}updateUI();}
function coopDisconnect(message){if(!coop.active)return;coopLeave();releaseMouse();if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});showTitleStep('roomChoice');coopStatus(message);$('roomContinue').hidden=true;}
function coopRoomUI(){const connected=!!coop.connection?.open;$('roomContinue').hidden=!connected;$('roomCode').textContent=coop.code||'------';$('roomStart').hidden=!coop.host||!coop.ready||!coop.remoteReady||coop.started;}
function coopConnect(connection){
 if(coop.connection){connection.close();return;}coop.connection=connection;
 connection.on('open',()=>{coopStatus('Your teammate joined. Both players can now choose their controls and customize.');coopSend({type:'hello',profile});coopRoomUI();});
 connection.on('data',coopReceive);connection.on('close',()=>{if(coop.connection===connection)coopDisconnect('Your teammate left the room. Create or join a room to play again.');});connection.on('error',()=>{if(coop.connection===connection)coopDisconnect('Connection interrupted. Please create or join a new room.');});
}
function coopOpenRoom(host){
 coopLeave();coop.active=true;coop.host=host;coop.ended=false;coop.stage=1;KEY='hollow-house-coop-v1';world=null;stageSaves={};best=2;level=1;coopStatus(host?'Creating your room...':'Connecting to the room...');$('roomContinue').hidden=true;
 const code=host?Array.from(crypto.getRandomValues(new Uint8Array(8)),n=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[n%32]).join(''):$('joinCode').value.trim().toUpperCase();
 if(!/^[A-Z2-9]{8}$/.test(code)){coopStatus('Enter the eight-character room code.');coop.active=false;return;}
 coop.code=code;coopRoomUI();
 try{coop.peer=host?new Peer('hollow-house-'+code):new Peer();coop.peer.on('open',()=>{if(host)coopStatus('Share this code with your friend. Keep this page open.');else coopConnect(coop.peer.connect('hollow-house-'+code,{reliable:true}));});coop.peer.on('connection',c=>{if(coop.host)coopConnect(c);else c.close();});coop.peer.on('error',e=>{coopStatus(e.type==='peer-unavailable'?'Room not found. Check the code and ask the host to keep their room open.':'Could not connect. Check your internet connection and try again.');$('roomContinue').hidden=true;});}catch{coopStatus('Multiplayer is unavailable in this browser. Try a current Chrome, Edge, or Safari browser.');}
}
function coopSelectUI(){showTitleStep('coopLevels');const grid=$('coopLevelGrid');grid.replaceChildren();COOP_LEVELS.forEach((name,i)=>{const b=document.createElement('button');b.className='haunted-stage';b.innerHTML='<span>CO-OP LEVEL '+(i+1)+'</span><strong>'+name+'</strong><small>Two floors / three relics / two hidden keys</small>';b.disabled=!coop.host;b.onclick=()=>{coop.stage=i+1;$('coopSelected').textContent=name;coop.ready=true;coopSend({type:'ready',profile,stage:coop.stage});coopRoomUI();};grid.append(b);});$('coopSelected').textContent=coop.host?'Choose a level, then wait for your teammate.':'The host chooses the level. You are ready.';if(!coop.host){coop.ready=true;coopSend({type:'ready',profile});}coopRoomUI();}
function coopApproach(item){return {x:item.x+item.nx*.85,y:item.y+item.ny*.85};}
function coopEnsureWardrobe(){
 if(world.furniture.some(w=>w.type==='wardrobe'))return;
 // Some random loop layouts have no natural alcoves. Carve one from a wall,
 // leaving every original passage open and the key reachable from that passage.
 for(let y=2;y<world.size-2;y++)for(let x=2;x<world.size-2;x++)if(world.grid[y][x]===1){for(const [nx,ny]of [[1,0],[-1,0],[0,1],[0,-1]])if(valid(x+nx+.5,y+ny+.5)){world.grid[y][x]=0;world.furniture.push({id:'coop-key-wardrobe',type:'wardrobe',x:x+.5,y:y+.5,nx,ny,height:.93});return;}}
 throw new Error('No reachable wardrobe alcove was available.');
}
function coopBuild(stage){
 coop.stage=stage;coop.keys={stair:false,exit:false};coop.clues=[false,false];coop.lives=3;coop.ended=false;coop.floors=[];
 for(let f=0;f<2;f++){level=1+(stage-1)*3+f;world=null;makeWorld();coopEnsureWardrobe();ensureWallPictures();const rooms=[...mazeDistanceMap({x:1.5,y:1.5})].sort((a,b)=>b[1]-a[1]);const at=i=>{const [x,y]=rooms[Math.min(i,rooms.length-1)][0].split(',').map(Number);return {x:x+.5,y:y+.5};};world.relics=world.relics.slice(0,f===0?1:2);world.relics.forEach((r,i)=>Object.assign(r,at(i*10+8),{taken:false}));world.relicLayoutVersion=2;world.stairs=f===0?at(0):{x:1.5,y:1.5};world.exit=f===0?{x:1.5,y:1.5}:world.stairs;world.clue=at(18);const wardrobes=world.furniture.filter(o=>o.type==='wardrobe');world.keyWardrobe=wardrobes[Math.min(stage-1,wardrobes.length-1)].id;world.coopFloor=f;coop.floors.push(world);}
 const horizontal=coop.floors[0].grid[1][2]===0;coop.players=[0,1].map(i=>({x:1.5+(horizontal?i*.35:0),y:1.5+(horizontal?0:i*.35),angle:horizontal?0:Math.PI/2,floor:0,stamina:100,invulnerable:4,profile:i===0?{...profile}:{...(coop.remoteProfile||profile)}}));level=stage;coop.started=true;coop.ready=true;coopBindWorld();
}
function coopLaunch(){coop.started=true;coop.ended=false;$('settingsHome').textContent='Leave room & return home';difficulty='normal';flashlightOn=true;syncFlashlight();closeTitle();mode='playing';keys={};resetJoystick();$('overlay').classList.add('hidden');$('start').onclick=()=>{mode='playing';keys={};$('overlay').classList.add('hidden');updateUI();};coopBindWorld();updateUI();}
function coopSnapshot(){return {type:'state',players:coop.players,keys:coop.keys,clues:coop.clues,lives:coop.lives,floors:coop.floors.map(f=>({enemy:f.enemy,relics:f.relics,wallPictures:f.wallPictures,time:f.time})),ended:coop.ended};}
function coopReceive(data){
 if(!data||typeof data!=='object')return;
 if(data.type==='lobby'&&!coop.host){coop.started=false;coop.ended=false;coop.ready=false;coop.remoteReady=false;coopSelectUI();return;}
 if(data.type==='hello'){coop.remoteProfile=coopSafeProfile(data.profile);}
 if(data.type==='ready'){coop.remoteProfile=coopSafeProfile(data.profile);coop.remoteReady=true;if(!coop.host&&Number.isInteger(data.stage)){coop.stage=data.stage;$('coopSelected').textContent=COOP_LEVELS[data.stage-1]||COOP_LEVELS[0];}coopRoomUI();}
 if(data.type==='start'&&!coop.host&&Array.isArray(data.floors)&&data.floors.length===2){Object.assign(coop,{floors:data.floors,players:data.players,stage:data.stage,keys:data.keys,clues:data.clues,lives:3});coopLaunch();}
 if(data.type==='move'&&coop.host&&coop.started&&!coop.ended){const p=coop.players[1],v=data.player;if(!v||v.floor!==p.floor)return;const saved=world;world=coop.floors[p.floor];if(Number.isFinite(v.x)&&Number.isFinite(v.y)&&distance(p,v)<1.8&&valid(v.x,v.y)){p.x=v.x;p.y=v.y;p.angle=Number.isFinite(v.angle)?v.angle:p.angle;p.gaitPhase=Number.isFinite(v.gaitPhase)?v.gaitPhase:0;p.motion=Math.max(0,Math.min(1,v.motion||0));p.running=!!v.running;}if(!v.hidingId){delete p.hidingId;p.hidingSeconds=0;}else{const w=world.furniture.find(w=>w.id===v.hidingId&&w.type==='wardrobe');if(w&&distance(p,w)<1.3){p.hidingId=w.id;}}p.profile=coopSafeProfile(data.profile);world=saved;}
 if(data.type==='interact'&&coop.host&&coop.started)coopInteract(1);
 if(data.type==='state'&&!coop.host&&coop.started){const local=coopLocal();const incoming=data.players?.[1];if(!incoming||!Array.isArray(data.floors))return;const changed=incoming.floor!==local.floor||incoming.respawn!==local.respawn||distance(incoming,local)>1.8;coop.players=data.players;if(!changed)Object.assign(coop.players[1],{x:local.x,y:local.y,angle:local.angle,lookOffset:local.lookOffset,gaitPhase:local.gaitPhase,motion:local.motion,stamina:local.stamina});coop.keys=data.keys;coop.clues=data.clues;coop.lives=data.lives;data.floors.forEach((f,i)=>Object.assign(coop.floors[i],f));coopBindWorld();updateUI();}
 if(data.type==='death'&&!coop.host)coopDeathScreen(data.player);
 if(data.type==='end'&&!coop.host)coopEnd(data.won);
}
function coopSafeProfile(p){p=p||{};return {name:String(p.name||'Traveler').slice(0,18),color:/^#[0-9a-f]{6}$/i.test(p.color)?p.color:COLORS[0],skin:/^#[0-9a-f]{6}$/i.test(p.skin)?p.skin:'#e3b18b',hair:['short','long','hood'].includes(p.hair)?p.hair:'short',gender:p.gender==='female'?'female':'male',outfit:['field','padded','tactical'].includes(p.outfit)?p.outfit:'field'};}
function coopHint(p){const f=coop.floors[p.floor];if(p.hidingId)return 'Leave the wardrobe before your air runs out.';if(distance(p,f.clue)<1&&!coop.clues[p.floor])return 'Read the torn letter';const w=f.furniture.find(w=>w.id===f.keyWardrobe);if(w&&distance(p,w)<1.3&&!coop.keys[p.floor===0?'stair':'exit'])return 'Search the brass-marked wardrobe';if(distance(p,f.stairs)<.85)return p.floor===0?(coop.keys.stair?'Go upstairs':'Stairwell locked: find the brass key'):'Go downstairs';if(p.floor===0&&distance(p,f.exit)<.85)return 'Unlock the front door';return '';}
function coopInteract(id=coopId()){
 if(!coop.started||coop.ended)return;if(!coop.host){coopSend({type:'interact'});return;}const p=coop.players[id],f=coop.floors[p.floor];if(p.hidingId)return;
 if(distance(p,f.clue)<1&&!coop.clues[p.floor]){coop.clues[p.floor]=true;coopNotice(p.floor===0?'The letter reads: The brass-marked wardrobe holds the stairwell key.':'The letter reads: Upstairs, search the brass-marked wardrobe for the front-door key.');}
 else {const w=f.furniture.find(w=>w.id===f.keyWardrobe),key=p.floor===0?'stair':'exit';if(w&&distance(p,w)<1.3&&!coop.keys[key]){if(!coop.clues[p.floor])coopNotice('The drawer has a hidden latch. Find the torn letter on this floor first.');else{coop.keys[key]=true;coopNotice(key==='stair'?'Brass key found. The stairs are unlocked.':'Exit key found. Gather all three relics and return downstairs together.');}}
 else if(distance(p,f.stairs)<.85){if(p.floor===0&&!coop.keys.stair)coopNotice('The staircase gate needs the brass key.');else{p.floor=1-p.floor;Object.assign(p,coop.floors[p.floor].stairs);p.x+=.1;p.invulnerable=3;delete p.hidingId;}}
 else if(p.floor===0&&distance(p,f.exit)<.85){if(!coop.keys.exit||coop.floors.some(f=>f.relics.some(r=>!r.taken)))coopNotice('The exit needs its key and all three relics.');else if(coop.players.some(p=>p.floor!==0||distance(p,f.exit)>1.5))coopNotice('Wait for your teammate at the front door.');else coopEnd(true);}}
 coopBindWorld();coopSend(coopSnapshot());updateUI();
}
function coopNotice(text){$('coopMessage').textContent=text;if(coop.host)coopSend({type:'notice',text});}
const coopDataReceiver=coopReceive;coopReceive=function(data){if(data?.type==='notice'){$('coopMessage').textContent=String(data.text).slice(0,250);return;}coopDataReceiver(data);};
function coopDeath(id){if(coop.ended)return;coop.lives--;const p=coop.players[id];Object.assign(p,{x:1.5,y:1.5,floor:0,stamina:100,invulnerable:5,respawn:(p.respawn||0)+1});delete p.hidingId;p.hidingSeconds=0;coop.floors.forEach(f=>{f.enemy.state='patrol';f.enemy.target=null;f.enemy.x=f.size-1.5;f.enemy.y=f.size-1.5;});coopSend(coopSnapshot());coopSend({type:'death',player:id});coopDeathScreen(id);if(coop.lives<=0)coopEnd(false);}
function coopDeathScreen(id){if(id!==coopId()){coopNotice('Your teammate was caught. '+coop.lives+' team hearts remain.');return;}catchSting();coop.scare=1.35;coopBindWorld();canvas.style.filter='none';flashlightOn=true;coopNotice('You were caught. '+coop.lives+' team hearts remain. Your relics and keys are safe.');}
function coopEnd(won){if(coop.ended)return;coop.ended=true;if(coop.host)coopSend({type:'end',won});if(won){wallet.coins+=150;saveWallet();let cleared=0;try{cleared=Number(localStorage.getItem('hollow-house-coop-cleared'))||0;}catch{}localStorage.setItem('hollow-house-coop-cleared',String(Math.max(cleared,coop.stage)));}mode=won?'won':'dead';keys={};releaseMouse();show(won?'TOGETHER, YOU ESCAPED':'THE HOUSE CLAIMED YOUR TEAM',won?'Both survivors made it out.':'No team hearts remain.',won?'Three relics, two keys, two floors. +150 coins each.':'This round is over. Start a fresh multiplayer level.','Return to multiplayer levels');$('start').onclick=()=>{coop.started=false;coop.ready=false;coop.remoteReady=false;coopSend({type:'lobby'});coopSelectUI();};updateUI();}
function coopTick(dt){
 if(!coop.started||coop.ended)return;coopBindWorld();const p=coopLocal(),before={x:p.x,y:p.y};p.profile={...profile};p.angle=(p.angle||0)+((keys.arrowright||keys.e?1:0)-(keys.arrowleft||keys.q?1:0))*2.1*dt;const forward=Math.max(-1,Math.min(1,(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0)+joystickInput.forward)),strafe=Math.max(-1,Math.min(1,(keys.d?1:0)-(keys.a?1:0)+joystickInput.strafe)),dx=Math.cos(p.angle)*forward-Math.sin(p.angle)*strafe,dy=Math.sin(p.angle)*forward+Math.cos(p.angle)*strafe,sprint=keys.shift&&(forward||strafe)&&p.stamina>0;if(!p.hidingId){const len=Math.max(1,Math.hypot(dx,dy));move(p,dx/len*(sprint?4.2:2.6)*dt,dy/len*(sprint?4.2:2.6)*dt);}updateLocomotion(p,before,dt);p.stamina=Math.max(0,Math.min(100,p.stamina+(sprint?-34:22)*dt));world.stamina=p.stamina;
 if(coop.host){for(let floor=0;floor<2;floor++){world=coop.floors[floor];world.player=coop.players.find(p=>p.floor===floor)||coopLocal();world.time+=dt;updateSpiders(dt);const present=coop.players.filter(p=>p.floor===floor);for(const visitor of present){world.player=visitor;updateWallPictures(dt/Math.max(1,present.length));}const e=world.enemy,old={x:e.x,y:e.y},players=present;for(const p of players){p.invulnerable=Math.max(0,(p.invulnerable||0)-dt);if(p.hidingId){p.hidingSeconds=(p.hidingSeconds||0)+dt;if(p.hidingSeconds>=10){coopDeath(coop.players.indexOf(p));world=coop.floors[floor];continue;}}for(const r of world.relics)if(!p.hidingId&&!r.taken&&distance(p,r)<.5)r.taken=true;}
 const target=players.filter(p=>!p.hidingId&&!p.invulnerable&&distance(e,p)<7&&sees(e,p)).sort((a,b)=>distance(e,a)-distance(e,b))[0];if(target){e.state='chase';e.target={x:target.x,y:target.y};e.timer=3;}else if(e.state==='chase'){e.state='search';e.timer=3;}if(e.state==='search'){e.timer-=dt;e.moveAngle=(e.lookBase||0)+Math.sin(world.time*3)*.65;if(e.timer<=0){e.state='patrol';e.target=null;}}if(!e.target||distance(e,e.target)<.3)e.target=patrolTarget();if(e.state!=='search'){const n=path(e,e.target),d=distance(e,n),step=Math.min(d,(e.state==='chase'?1.9:1.1)*dt);if(d>.04)move(e,(n.x-e.x)/d*step,(n.y-e.y)/d*step);}updateLocomotion(e,old,dt,e.state==='chase',true);for(const p of players)if(!p.hidingId&&!p.invulnerable&&distance(p,e)<.45)coopDeath(coop.players.indexOf(p));}}
 coop.scare=Math.max(0,(coop.scare||0)-dt);coopBindWorld();coop.clock+=dt;coop.netClock+=dt;if(coop.netClock>=.1){coop.netClock=0;if(coop.host)coopSend(coopSnapshot());else coopSend({type:'move',player:p,profile});}updateUI();
}
tick=function(dt){if(coop.started)return coopTick(dt);return solo.tick(dt);};
persist=function(){if(coop.active)return;return solo.persist();};
updateUI=function(){solo.updateUI();$('coopHud').hidden=!coop.started;$('coopInteract').hidden=!coop.started||mode!=='playing';if(coop.started&&world){const p=coopLocal(),hint=coopHint(p);$('best').textContent='Co-op level '+coop.stage+' / 3';$('difficulty').textContent=COOP_LEVELS[coop.stage-1]+' / two-floor co-op';$('floor').textContent='0'+(p.floor+1);$('relics').textContent='RELICS '+coop.floors.flatMap(f=>f.relics).filter(r=>r.taken).length+' / 3';$('coopObjectives').textContent='Floor '+(p.floor+1)+' / 2 | Stair key: '+(coop.keys.stair?'found':'missing')+' | Exit key: '+(coop.keys.exit?'found':'missing');$('coopTeammate').textContent=(coop.players[1-coopId()]?.profile?.name||'Teammate')+' — floor '+((coop.players[1-coopId()]?.floor||0)+1);$('coopInteract').textContent=(hint||'Interact')+' (R)';$('coopInteract').disabled=!hint||!!p.hidingId;$('saveLabel').textContent='Live co-op room '+coop.code;}};
goHome=function(showTitle=true){if(showTitle&&coop.active)coopLeave();return solo.goHome(showTitle);};
$('titlePlay').onclick=()=>{unlockAudio();syncTitleAudio();showTitleStep('playChoice');};
$('chooseSolo').onclick=()=>{coopLeave();$('start').onclick=solo.start;showTitleStep('deviceChoice');};
$('chooseMultiplayer').onclick=()=>{showTitleStep('roomChoice');coopStatus('Create a room or enter your friend\'s eight-character code.');coopRoomUI();};
$('playBack').onclick=openTitle;$('roomBack').onclick=()=>{coopLeave();showTitleStep('playChoice');};
$('createRoom').onclick=()=>coopOpenRoom(true);$('joinRoom').onclick=()=>coopOpenRoom(false);
$('copyRoom').onclick=async()=>{try{await navigator.clipboard.writeText(coop.code);coopStatus('Room code copied. Send it to your friend.');}catch{coopStatus('Your room code is '+coop.code+'.');}};
$('roomContinue').onclick=()=>showTitleStep('deviceChoice');
for(const id of ['chooseComputer','choosePhone']){const original=$(id).onclick;$(id).onclick=()=>{if(!coop.active)return original();setDevice(id==='choosePhone'?'phone':'computer');coopSelectUI();};}
$('deviceBack').onclick=()=>showTitleStep(coop.active?'roomChoice':'playChoice');
$('roomStart').onclick=()=>{if(!coop.host||!coop.ready||!coop.remoteReady||!coop.connection?.open)return;coopBuild(coop.stage);coopSend({type:'start',floors:coop.floors,players:coop.players,stage:coop.stage,keys:coop.keys,clues:coop.clues});coopLaunch();};
$('coopLevelsBack').onclick=()=>showTitleStep('deviceChoice');
$('coopInteract').onclick=()=>coopInteract();
window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r'&&!e.repeat&&mode==='playing'&&coop.started&&!['INPUT','SELECT'].includes(document.activeElement.tagName))coopInteract();});
// The host keeps the shared simulation running when inspecting menus; local input stays still.
setInterval(()=>{if(coop.host&&coop.started&&!coop.ended&&mode!=='playing'){keys={};coopTick(.05);}},50);
const coopStartSolo=solo.start;$('start').onclick=()=>{if(coop.started){mode='playing';keys={};$('overlay').classList.add('hidden');updateUI();}else coopStartSolo();};

const coopCustomizeDone=$('customizeDone').onclick;$('customizeDone').onclick=()=>{coopCustomizeDone();if(coop.active)coopSend({type:coop.ready?'ready':'hello',profile,stage:coop.host?coop.stage:undefined});};
const coopOpenMenu=openMenu;openMenu=function(id){if(coop.active&&id==='levelsDialog'){if(coop.started&&!coop.ended){coopNotice('Finish this round or return home to leave the room.');return;}coopSelectUI();return;}coopOpenMenu(id);};
const coopPause=pause;pause=function(){coopPause();if(coop.started&&!coop.ended&&mode==='paused')$('overlayText').textContent='Your movement is paused. The shared house stays live: your teammate and Slenderman continue moving. Leave your wardrobe before its 10-second air limit.';};
const coopReset=$('reset').onclick;$('reset').onclick=()=>{if(coop.active){coopNotice('Return home to leave this live room. Solo progress is kept separately.');return;}coopReset();};

const coopDraw=draw;draw=function(){coopDraw();if(coop.started&&coop.scare>0)renderShadowJumpscare(ctx,1.35-coop.scare);};
