const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require('../.tools/browser/node_modules/playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'}),page=await browser.newPage({viewport:{width:1360,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='warning'&&m.text().includes('fallback'))errors.push(m.text())});
 await page.goto(process.env.GAME_URL||'http://127.0.0.1:8001');await page.waitForFunction(()=>REAL_WALL?.complete&&REAL_WALL.naturalWidth>0);await page.evaluate(()=>{$('start').onclick();mode='paused';$('overlay').classList.add('hidden');draw()});
 assert.equal(await page.evaluate(()=>!!GPU),true);assert.equal(await page.evaluate(()=>GPU.slenderHead.count>5000&&GPU.slenderSuit.count>4000&&GPU.sleeve.count>3000&&GPU.lapels.count===6&&GPU.shirt.count===3),true);assert.equal(await page.evaluate(()=>GPU.gl.getError()),0);
 assert.equal(await page.evaluate(()=>{GPU.gl.bindFramebuffer(GPU.gl.FRAMEBUFFER,GPU.shadowFramebuffer);const ready=GPU.gl.checkFramebufferStatus(GPU.gl.FRAMEBUFFER)===GPU.gl.FRAMEBUFFER_COMPLETE;GPU.gl.bindFramebuffer(GPU.gl.FRAMEBUFFER,null);return ready}),true);
 const stats=await page.evaluate(()=>{const times=[];for(let i=0;i<8;i++){const start=performance.now();draw();times.push(performance.now()-start)}return {milliseconds:times.sort((a,b)=>a-b)[4],antialias:GPU.gl.getContextAttributes().antialias,vertices:GPU.scene.count}});
 assert(stats.vertices>1000);assert(stats.antialias);
 fs.mkdirSync('.tools/qa',{recursive:true});await page.locator('#game').screenshot({path:'.tools/qa/gpu-normal.png'});
 await page.evaluate(()=>{setDevice('phone');draw()});assert.equal(await page.evaluate(()=>GPU.surface.width),800);assert.equal(await page.evaluate(()=>GPU.shadowSize),512);assert.equal(await page.evaluate(()=>GPU.gl.getError()),0);
 await page.evaluate(()=>{difficulty='psycho';flashlightOn=false;draw()});const dark=await page.evaluate(()=>{let sum=0,d=ctx.getImageData(200,130,500,340).data;for(let i=0;i<d.length;i+=4)sum+=d[i]+d[i+1]+d[i+2];return sum});
 await page.evaluate(()=>{flashlightOn=true;draw()});const lit=await page.evaluate(()=>{let sum=0,d=ctx.getImageData(200,130,500,340).data;for(let i=0;i<d.length;i+=4)sum+=d[i]+d[i+1]+d[i+2];return sum});assert(lit>dark*2);
 await page.evaluate(()=>{difficulty='normal';setDevice('computer');world.size=9;world.grid=Array.from({length:9},(_,y)=>Array.from({length:9},(_,x)=>x===0||x===8||y===0||y===8?1:0));world.furniture=[];world.player={x:4.5,y:3.5,angle:Math.PI/2};world.enemy={x:5.5,y:5.0,state:'patrol',target:null,timer:0,moveAngle:-Math.PI/2};cameraMode='third';draw()});assert(await page.evaluate(()=>GPU.floorDebrisCount>0));await page.locator('#game').screenshot({path:'.tools/qa/gpu-characters.png'});assert.equal(await page.evaluate(()=>GPU.gl.getError()),0);
 const shadowChanges=await page.evaluate(()=>{draw();const before=ctx.getImageData(0,0,1000,700).data.slice(),original=renderGpuShadow;try{renderGpuShadow=(g,p,h)=>{const light=original(g,p,h);g.gl.bindFramebuffer(g.gl.FRAMEBUFFER,g.shadowFramebuffer);g.gl.clear(g.gl.DEPTH_BUFFER_BIT);g.gl.bindFramebuffer(g.gl.FRAMEBUFFER,null);return light};draw();const after=ctx.getImageData(0,0,1000,700).data;let changed=0;for(let i=0;i<before.length;i+=4)if(Math.abs(before[i]-after[i])+Math.abs(before[i+1]-after[i+1])+Math.abs(before[i+2]-after[i+2])>4)changed++;return changed;}finally{renderGpuShadow=original}});assert(shadowChanges>30,'Flashlight shadow map must change visible pixels');
 await page.evaluate(()=>{gpuUnavailable=true;GPU=null;draw()});assert.equal(await page.evaluate(()=>!!VIEW.buffer),true);
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: GPU scene/model rendering, anti-aliasing, shader errors, phone resolution, Psycho blackout/flashlight, and canvas fallback. Median desktop draw: '+stats.milliseconds.toFixed(1)+' ms (headless test browser).');
})().catch(e=>{console.error(e);process.exit(1)});
