// Development check: npm install --prefix .tools/browser playwright
const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require('../.tools/browser/node_modules/playwright');
const url=process.env.GAME_URL||'http://127.0.0.1:8001';
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
 const errors=[];const desktop=await browser.newContext({viewport:{width:1360,height:1000}});const page=await desktop.newPage();page.on('pageerror',e=>errors.push(e.message));
 fs.mkdirSync('.tools/qa',{recursive:true});
 await page.goto(url);await page.waitForTimeout(4700);
 assert(await page.locator('#titleScreen').isVisible());assert.equal((await page.request.get(url+'/assets/haunted-house.png')).status(),200);
 await page.screenshot({path:'.tools/qa/title-desktop.png'});
 await page.locator('#titleAudio').click();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>audio.state),'running');assert(await page.evaluate(()=>!!musicBus));
 await page.locator('#titlePlay').click();await page.locator('#chooseComputer').click();await page.locator('#chooseNormal').click();
 assert.equal(await page.evaluate(()=>mode),'playing');assert.equal(await page.evaluate(()=>difficulty),'normal');assert(await page.locator('#titleScreen').isHidden());
 await page.screenshot({path:'.tools/qa/normal-desktop.png'});
 await page.keyboard.press('f');assert.equal(await page.evaluate(()=>flashlightOn),false);await page.keyboard.press('f');
 await page.evaluate(()=>{best=1;persist()});
 await page.locator('#settingsButton').click();await page.locator('#settingsHome').click();assert(await page.locator('#titleScreen').isVisible());
 await page.locator('#titlePlay').click();await page.locator('#chooseComputer').click();await page.locator('#choosePsycho').click();assert.equal(await page.evaluate(()=>best),0);
 assert.equal(await page.evaluate(()=>KEY),'hollow-house-psycho-v1');
 await page.evaluate(()=>{pause();chooseDifficulty('normal')});assert.equal(await page.evaluate(()=>best),1);
 await page.locator('#fullscreenButton').click();await page.waitForTimeout(200);assert.equal(await page.locator('#fullscreenButton').textContent(),'Exit fullscreen');
 await page.locator('#fullscreenButton').click();assert.equal(await page.locator('#fullscreenButton').textContent(),'Fullscreen');
 const phoneContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});const phone=await phoneContext.newPage();phone.on('pageerror',e=>errors.push(e.message));
 await phone.goto(url);await phone.waitForTimeout(4500);await phone.screenshot({path:'.tools/qa/title-phone.png'});
 await phone.locator('#titlePlay').click();await phone.locator('#choosePhone').click();await phone.locator('#choosePsycho').click();
 assert(await phone.locator('#phoneControls').isVisible());assert.equal(await phone.evaluate(()=>flashlightOn),false);assert.equal(await phone.evaluate(()=>sound),true);
 const brightness=()=>phone.evaluate(()=>{let sum=0;const data=ctx.getImageData(200,130,500,340).data;for(let i=0;i<data.length;i+=4)sum+=data[i]+data[i+1]+data[i+2];return sum});
 await phone.waitForTimeout(200);const dark=await brightness();await phone.screenshot({path:'.tools/qa/psycho-dark-phone.png'});
 await phone.locator('#phoneFlashlight').click();await phone.waitForTimeout(100);assert.equal(await phone.evaluate(()=>flashlightOn),true);assert((await brightness())>dark*2);
 await phone.screenshot({path:'.tools/qa/psycho-lit-phone.png'});
 // Real touch events exercise pointer capture and independent joystick/look input.
 const cdp=await phoneContext.newCDPSession(phone);const box=await phone.locator('#joystick').boundingBox();
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width/2,y:box.y+box.height/2}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+box.width/2,y:box.y+box.height/2-30}]});
 assert((await phone.evaluate(()=>joystickInput.forward))>.7);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await phone.evaluate(()=>joystickInput.forward),0);
 const canvas=await phone.locator('#game').boundingBox(),angle=await phone.evaluate(()=>world.player.angle||0);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:canvas.x+150,y:canvas.y+110}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:canvas.x+220,y:canvas.y+140}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert((await phone.evaluate(()=>world.player.angle))>angle+.4);
 const run=await phone.locator('#phoneSprint').boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:run.x+20,y:run.y+20}]});assert.equal(await phone.evaluate(()=>keys.shift),true);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await phone.evaluate(()=>!!keys.shift),false);
 const before=await phone.evaluate(()=>({level,best,relics:world.relics.length}));await phone.evaluate(()=>{psychoCountdown=0;updatePsycho(.01)});assert((await phone.evaluate(()=>falseScareTime))>0);assert.equal(await phone.evaluate(()=>mode),'playing');assert.deepEqual(await phone.evaluate(()=>({level,best,relics:world.relics.length})),before);
 await phone.evaluate(()=>{setEffects(true);creepyScream()});assert((await phone.evaluate(()=>screamVoices.size))>0);await phone.evaluate(()=>setEffects(false));assert.equal(await phone.evaluate(()=>screamVoices.size),0);
 await phone.setViewportSize({width:844,height:390});await phone.waitForTimeout(150);await phone.screenshot({path:'.tools/qa/phone-landscape.png'});
 assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await phone.locator('#phonePause').click();assert.equal(await phone.evaluate(()=>mode),'paused');assert.equal(await phone.evaluate(()=>joystickInput.forward),0);assert(await phone.locator('#phoneControls').isHidden());
 assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);console.log('PASS: title image and audio, device/mode flow, isolated saves, fullscreen, phone joystick/swipe/sprint/pause, blackout/flashlight, harmless scares, scream mute cleanup, and responsive width.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
