const assert=require('node:assert/strict'),{chromium}=require('../.tools/browser/node_modules/playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
 const contexts=await Promise.all([browser.newContext({viewport:{width:1360,height:950}}),browser.newContext({viewport:{width:390,height:950}})]),pages=await Promise.all(contexts.map(c=>c.newPage())),[host,guest]=pages,errors=[];
 for(const page of pages){page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.GAME_URL||'http://127.0.0.1:8010');assert(await page.locator('#titleShop').isHidden());await page.locator('#titlePlay').click();assert(await page.locator('#playChoice').isVisible());await page.locator('#chooseMultiplayer').click();assert(await page.locator('#roomChoice').isVisible());}
 console.log('Creating live room...');await host.locator('#createRoom').click();await host.waitForFunction(()=>coop.peer?.open,{},{timeout:45000});const code=await host.locator('#roomCode').textContent();assert.match(code,/^[A-Z2-9]{8}$/);await host.locator('#joinCode').fill(code);await host.locator('#joinRoom').click();assert.match(await host.locator('#roomStatus').textContent(),/already hosting/);assert(await host.evaluate(()=>coop.host&&coop.peer.open&&!coop.peer.destroyed));assert.equal(await host.locator('#roomCode').textContent(),code);await host.locator('#joinCode').fill('BAD');await host.locator('#joinRoom').click();assert(await host.evaluate(()=>coop.host&&coop.peer.open));await guest.locator('#joinCode').fill(code);await guest.locator('#joinRoom').click();await Promise.all(pages.map(p=>p.waitForFunction(()=>coop.connection?.open,{},{timeout:45000})));
 console.log('Both peers connected.');await host.locator('#roomContinue').click();await guest.locator('#roomContinue').click();await host.locator('#chooseComputer').click();await guest.locator('#choosePhone').click();await guest.evaluate(()=>{profile.name='Ivy';profile.color='#b39acd';profile.gender='female';coopSend({type:'ready',profile});});await host.locator('#coopLevelGrid button').first().click();await host.waitForFunction(()=>coop.remoteReady);await host.locator('#roomStart').click();await guest.waitForFunction(()=>coop.started);await Promise.all(pages.map(p=>p.evaluate(()=>{mode='playing';document.hasFocus=()=>true;})));
 assert.equal(await guest.evaluate(()=>coop.floors.length),2);assert.equal(await host.evaluate(()=>coop.floors.flatMap(f=>f.relics).length),3);assert.equal(await host.evaluate(()=>coop.players[1].profile.name),'Ivy');assert.equal(await host.evaluate(()=>coopTeammates().length),1);assert.equal(await guest.evaluate(()=>coopTeammates().length),1);
 await host.evaluate(()=>{for(const p of coop.players)p.invulnerable=100;coopSend(coopSnapshot());});
 const initial=await host.evaluate(()=>({x:coop.players[1].x,y:coop.players[1].y}));await guest.evaluate(()=>{mode='playing';coopLocal().angle=world.grid[1][2]===0?0:Math.PI/2;});await guest.keyboard.down('w');await host.waitForFunction(v=>Math.hypot(coop.players[1].x-v.x,coop.players[1].y-v.y)>.25,initial,{timeout:8000});await guest.keyboard.up('w');
 await host.evaluate(()=>{mode='paused';Object.assign(coop.players[0],coop.floors[0].stairs);coopInteract(0);});assert.equal(await host.evaluate(()=>coopLocal().floor),1);assert.equal(await host.evaluate(()=>coop.keys.stair),false);await host.evaluate(()=>{Object.assign(coop.players[0],coop.floors[1].stairs);coopInteract(0);});assert.equal(await host.evaluate(()=>coopLocal().floor),0);
 await host.evaluate(()=>{Object.assign(coop.players[1],coop.floors[0].stairs);coop.players[1].respawn=(coop.players[1].respawn||0)+1;coopSend(coopSnapshot());});await guest.waitForFunction(()=>Math.hypot(coopLocal().x-world.stairs.x,coopLocal().y-world.stairs.y)<.85);await guest.keyboard.press('r');await guest.waitForFunction(()=>coopLocal().floor===1);assert.equal(await host.evaluate(()=>coop.players[1].floor),1);await guest.keyboard.press('r');await guest.waitForFunction(()=>coopLocal().floor===0);
 // Stairs are usable immediately; clues still gate the exit keys.
 await host.evaluate(()=>{mode='paused';const p=coop.players[0],f=coop.floors[0];Object.assign(p,coopApproach(f.furniture.find(w=>w.id===f.keyWardrobe)));coopInteract(0);});assert.equal(await host.evaluate(()=>coop.keys.stair),false);
 await host.evaluate(()=>{const p=coop.players[0];Object.assign(p,coop.floors[0].clue);coopInteract(0);Object.assign(p,coopApproach(coop.floors[0].furniture.find(w=>w.id===coop.floors[0].keyWardrobe)));coopInteract(0);});assert.equal(await host.evaluate(()=>coop.keys.stair),true);await guest.waitForFunction(()=>coop.keys.stair);
 await host.evaluate(()=>{const p=coop.players[0];Object.assign(p,coop.floors[0].stairs);coopInteract(0);});assert.equal(await host.evaluate(()=>coopLocal().floor),1);await guest.waitForFunction(()=>coop.players[0].floor===1);assert.equal(await guest.evaluate(()=>coopTeammates().length),0);
 await host.evaluate(()=>{const p=coop.players[0],f=coop.floors[1];Object.assign(p,f.clue);coopInteract(0);Object.assign(p,coopApproach(f.furniture.find(w=>w.id===f.keyWardrobe)));coopInteract(0);});assert.equal(await host.evaluate(()=>coop.keys.exit),true);await guest.waitForFunction(()=>coop.keys.exit);
 // Both browsers render their teammate's chosen 3D appearance.
 await host.evaluate(()=>{const p=coop.players[0];Object.assign(p,coop.floors[1].stairs);coopInteract(0);p.x=1.5;p.y=1.5;p.angle=Math.PI/2;coop.players[1].x=1.5;coop.players[1].y=2.1;coopSend(coopSnapshot());draw();});assert.equal(await host.evaluate(()=>GPU.gl.getError()),0);await host.screenshot({path:'.tools/qa/coop-host.png'});await guest.screenshot({path:'.tools/qa/coop-phone.png'});
 // Team hearts preserve all shared objectives until the third catch.
 await host.evaluate(()=>{coop.floors[0].relics[0].taken=true;coopDeath(1);});await guest.waitForFunction(()=>coop.lives===2);assert.equal(await guest.evaluate(()=>coop.floors[0].relics[0].taken),true);assert.equal(await guest.evaluate(()=>coop.keys.exit),true);
 await host.evaluate(()=>{coopDeath(0);coopDeath(1);});await guest.waitForFunction(()=>coop.ended);assert.equal(await guest.evaluate(()=>mode),'dead');assert.equal(await host.evaluate(()=>coop.lives),0);
 console.log('Round ended; testing restart.');await host.locator('#start').click();await guest.waitForFunction(()=>!coop.started);await host.locator('#coopLevelGrid button').nth(1).click();await host.waitForFunction(()=>coop.remoteReady);await host.locator('#roomStart').click();await guest.waitForFunction(()=>coop.started&&!coop.ended);assert.equal(await host.evaluate(()=>coop.lives),3);assert.equal(await host.evaluate(()=>coop.keys.exit),false);
 await host.evaluate(()=>{mode='paused';coop.keys.stair=true;coop.keys.exit=true;coop.floors.forEach(f=>f.relics.forEach(r=>r.taken=true));coop.players.forEach(p=>Object.assign(p,coop.floors[0].exit,{floor:0,invulnerable:100}));coopInteract(0);});await guest.waitForFunction(()=>coop.ended);assert.equal(await host.evaluate(()=>wallet.coins),150);assert.equal(await guest.evaluate(()=>wallet.coins),150);assert.equal(await host.evaluate(()=>mode),'won');
 assert.deepEqual(errors,[]);for(const page of pages)assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await host.getByRole('button',{name:'Back to home',exact:true}).click();await guest.waitForFunction(()=>!coop.active);assert(await guest.locator('#roomChoice').isVisible());await browser.close();console.log('PASS: real WebRTC room, desktop/phone, visible custom teammate, two floors, clue/key gates, shared relics/hearts, three-death reset, replay, rewards and disconnect.');
})().catch(e=>{console.error(e);process.exit(1)});
